version: "3"

services:
  db:
    image: "mongo:4.4"
    ports:
      - 27017:27017
    restart: on-failure
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
